# Generated by Django 2.2.5 on 2019-09-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title2',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
